uploadTester/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'uploadTester.views.home', name='home'),
    url(r'^form$', 'uploadTester.views.form_submit', name='form_submit'),
    url(r'^vp$', 'uploadTester.views.videopost', name='videoPost'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

uploadTester/forms.py
from django import forms


class UploadForm(forms.Form):
    time = forms.CharField(max_length=20, widget=forms.HiddenInput())
    size = forms.CharField(max_length=20, widget=forms.HiddenInput())

uploadTester/views.py
from __future__ import division
from django.shortcuts import render, redirect, HttpResponse
from .forms import UploadForm
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages

def humanize_bytes(bytes, precision=1):
    """Return a humanized string representation of a number of bytes.

    Assumes `from __future__ import division`.


    '1.3 GB'
    """
    abbrevs = (
        (1<<50L, 'PB'),
        (1<<40L, 'TB'),
        (1<<30L, 'GB'),
        (1<<20L, 'MB'),
        (1<<10L, 'kB'),
        (1, 'bytes')
    )
    if bytes == 1:
        return '1 byte'
    for factor, suffix in abbrevs:
        if bytes >= factor:
            break
    return '%.*f %s' % (precision, bytes / factor, suffix)

def home(request):
    form = UploadForm()
    return render(request, "welcome.html", { "form": form })


def form_submit(request):
    time_took = None
    size = None
    if request.POST:
        form = UploadForm(request.POST)
        if form.is_valid():
            time_took = form.cleaned_data['time']
            size = form.cleaned_data['size']
            size = humanize_bytes(long(size))
            messages.add_message(request, messages.INFO,'It took %s seconds to upload %s.' % (time_took, size) )
    return redirect('home')


import json

@csrf_exempt
def videopost(request):
    serialized = {"coolness":"idone"}
    if request.POST:
        serialized = {"coolness":"done"}

    return HttpResponse(json.dumps(serialized), mimetype="application/json")

uploadTester/templates/welcome.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <script src="http://code.jquery.com/jquery-1.11.0.min.js" type="text/javascript"></script>
</head>
<body>

{% if messages %}
        {% for message in messages %}
            <h3{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</h3>
        {% endfor %}
    </ul>
{% endif %}

<form id="fileform" enctype="multipart/form-data" action="{% url 'videoPost' %}" method="POST">
    <input type="file" id="f" name="file"/>
</form>

<form id="timeform" enctype="multipart/form-data" action="{% url 'form_submit' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <br/>
    <br/>
    <input type="submit"/>Time It!</input>
    <h2 id="uploading"></h2>
</form>
<progress min="0" max="100" value="0">0% complete</progress>


<script type="text/javascript">
    var uploadFile;
    var startTime;

    $(':file').change(function(){
        uploadFile= this.files[0];
    });

    function upload(blobOrFile) {
        var xhr = new XMLHttpRequest();
        xhr.open('POST', '{% url 'videoPost' %}', true);
        xhr.onload = function(e) {  };

        // Listen to the upload progress.
        var progressBar = document.querySelector('progress');
        xhr.upload.onprogress = function(e) {
            if (e.lengthComputable) {
                progressBar.value = (e.loaded / e.total) * 100;
                progressBar.textContent = progressBar.value; // Fallback for unsupported browsers.
            }
        };

        xhr.send(blobOrFile);
    }

    function sendFile(){
        var form = $('#fileform').get(0);
        var formData = new FormData(form);
        var file = $('#f').get(0).files[0];
        $('#uploading').text('Uploading please wait...');

        $('#id_size').val(file.size);
        var xhr = new XMLHttpRequest();
        formData.append('myfile', file);
        xhr.open('POST', '{% url 'videoPost' %}', true);
        // Listen to the upload progress.
{#        var progressBar = document.querySelector('progress');#}
{#        xhr.upload.onprogress = function(e) {#}
{#            if (e.lengthComputable) {#}
{#                progressBar.value = (e.loaded / e.total) * 100;#}
{#                progressBar.textContent = progressBar.value; // Fallback for unsupported browsers.#}
{#            }#}
{#        };#}

        xhr.upload.onprogress = function(evt)
        {
                    var progressBar = document.querySelector('progress');
            if (evt.lengthComputable)
            {
                var percentComplete = parseInt((evt.loaded / evt.total) * 100);
                progressBar.value = percentComplete;
                progressBar.textContent = progressBar.value; // Fallback for unsupported browsers.
            }
        };
        startTime = Date.now();

        xhr.onreadystatechange = function(){
                            if (this.readyState == 4){
                                if(( this.status >=200 && this.status < 300 ) || this.status == 304){
                                    $('#id_time').val((Date.now() - startTime)/1000);
                                    $('#timeform').submit();
                                }
                            }
                        }

        xhr.send(formData);

    }

        $('input[type=submit]').click(function(e) {
            e.preventDefault();

            sendFile();
{#            upload(uploadFile);#}
{#            var xhr = new XMLHttpRequest();#}
{#            xhr.open('POST', '{% url 'videoPost' %}', true);#}
{#            xhr.setRequestHeader('accept', 'application/json');#}
{#            xhr.setRequestHeader('access-control-allow-origin', '*');#}
{#            xhr.setRequestHeader('content-type', 'video/mp4');#}
{#            starTime = Date.now();#}
{#            var formData = new FormData();#}
{#            formData.append("thefile", uploadFile);#}
{#            xhr.send(formData);#}
{#            xhr.onreadystatechange = function(){#}
{#                if (this.readyState == 4){#}
{#                    if(( this.status >=200 && this.status < 300 ) || this.status == 304){#}
{#                        $('#id_time').val((Date.now() - startTime)/1000);#}
{#                        $('#timeform').submit();#}
{#                    }#}
{#                }#}
{#            }#}
        });

</script>
</body>
</html>